### ISSUE TITLE
running error

### ISSUE THREAD

**Issue by jizefeng0810** [bradyz/task-distillation#2]
Thanks for sharing the code! 
I enter the command at the terminal: python -m policy_transfer.eval --agent_class ImageAgent --debug --port 2000 --pid 1 --agent_args ./weights/model_020.pth
But the program reported an error：
OMP: Error #15: Initializing libiomp5md.dll, but found libiomp5md.dll already initialized.
OMP: Hint This means that multiple copies of the OpenMP runtime have been linked into the program. That is dangerous, since it can degrade performance or cause incorrect results. The best thing to do is to ensure that only a single OpenMP runtime is linked into the process, e.g. by avoiding static linking of th
e OpenMP runtime in any library. As an unsafe, unsupported, undocumented workaround you can set the environment variable KMP_DUPLICATE_LIB_OK=TRUE to allow the program to continue to execute, but that may cause crashes or silently produce incorrect results. For more information, please see http://www.intel.com/
software/products/support/.

Can you help me solve this error?

**Comment by bradyz** [comment]
From https://github.com/openai/spinningup/issues/16

try `conda install nomkl`? if you're using conda

**Comment by jizefeng0810** [comment]
ok，i solve this problem, thank you for your answer

**Comment by jizefeng0810** [comment]
I have a question about Carla. How do you add the Town06 map in Carla? I run Carla version 0.9.9 on win10. I only run Town01-05 map. I can not run the evaluation.

**Comment by bradyz** [comment]
see the "Import additional assets" in the [CARLA installation quickstart](https://carla.readthedocs.io/en/latest/start_quickstart/)
