### ISSUE TITLE
How to collect the data?

### ISSUE THREAD

**Issue by jizefeng0810** [bradyz/task-distillation#3]
Hi,
I am trying to collect my own data. However, I don't know how to generate the bird view on Carla. Could you offer such scripts to collect data?  Thanks.

**Comment by jizefeng0810** [comment]
I want to know how to collect Carla's birdview in this project.
Why is the collected birdview saved as .npy instead of .png file. And why is the size (320*320*7)? There are 7 channels?  And the code ended up using only 2 channels. I want to know the details of this conversion. Thank you for your answer.

**Comment by bradyz** [comment]
there are in fact 7 channels, this is because the birdview rendering code saves additional information (traffic lights x 3, pedestrians, vehicles, road, lane markings)
but in our experiments, we only consider vehicles and road

**Comment by bradyz** [comment]
i'll clean up the code we used for data collection and upload this today! ill post here when it's up.

**Comment by jizefeng0810** [comment]
> i'll clean up the code we used for data collection and upload this today! ill post here when it's up.

Thank you very much for your reply. Looking forward to your code.

**Comment by bradyz** [comment]
check out `policy_transfer/collect_data.py` for full implementation and additional command line args.

Start up the CARLA 0.9.6 server,
then, from the top level directory, run

```
python3 -m policy_transfer.collect_data --debug
```

you should see something like this

![image](https://user-images.githubusercontent.com/7716849/93000290-0b2ac400-f4ed-11ea-9eaa-c311fcc184dd.png)

you can remove the `--debug` flag if you don't have a display.

**Comment by jizefeng0810** [comment]
> check out `policy_transfer/collect_data.py` for full implementation and additional command line args.
> 
> Start up the CARLA 0.9.6 server,
> then, from the top level directory, run
> 
> ```
> python3 -m policy_transfer.collect_data --debug
> ```
> 
> you should see something like this
> 
> ![image](https://user-images.githubusercontent.com/7716849/93000290-0b2ac400-f4ed-11ea-9eaa-c311fcc184dd.png)
> 
> you can remove the `--debug` flag if you don't have a display.

I ran the script very well. Thank you for your prompt reply.
